name: IPTV Channel Detection

on:
  # 手动触发
  workflow_dispatch:
  # 每周日凌晨2点自动触发
  schedule:
    - cron: '0 2 * * 0'

jobs:
  detect-channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run detection script
        run: |
          python all-z-j-new.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update channel list"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: iptv-output
          path: output/
          retention-days: 30
