name: IPTV Channel Detection

on:
  # 手动触发
  workflow_dispatch:
  # 每天凌晨2点自动触发
  schedule:
    - cron: '0 2 * * *'

jobs:
  detect-channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run script
        run: python all-z-j-new.py --jsmpeg jsmpeg_hosts.csv --txiptv txiptv_hosts.csv --output itvlist

      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: output-files
          path: output/
