name: 更新IPTV源

# 触发条件：定时触发和手动触发
on:
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v3
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: 运行IPTV处理脚本
        run: |
          python unicast.py --top 20
          
      - name: 检查是否有文件变更
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: 提交更新后的文件
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/ speed.log txt.tmp downloads/
          git commit -m "自动更新IPTV源: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
