name: 更新IPTV直播源unicast

on:
  workflow_dispatch:      # 允许手动触发
  schedule:               # 自动定时运行（每天凌晨2点UTC）
    - cron: '0 2 * * *'

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run IPTV Python script
        run: |
          mkdir -p dist
          python mobileunicast/unicast.py

      - name: Upload IPTV M3U file
        uses: actions/upload-artifact@v4
        with:
          name: iptv_live
          path: output/iptv_live.m3u
          if-no-files-found: create
