name: 自动更新 IPTV playlist

on:
  workflow_dispatch:
    inputs:
      top:
        description: '每频道保留最快N个源'
        required: false
        default: '10'
      proxy:
        description: 'http://127.0.0.1:7897'
        required: false
        default: ''
  schedule:
    # 每天凌晨3点（UTC+8 为上午11点）
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Generate IPTV playlist
        id: generate
        run: |
          python mobileunicast/unicast.py \
            --top "${{ github.event.inputs.top || 10 }}" \
            $([ -z "${{ github.event.inputs.proxy }}" ] || echo "--proxy '${{ github.event.inputs.proxy }}'")

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动生成 IPTV 源文件: $(date +'%Y-%m-%d %H:%M:%S')"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: 'output/iptv.*'

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-output
          path: output/iptv.*
