name: IPTV Unicast Update

on:
  workflow_dispatch:
    inputs:
      top:
        description: '每个频道最多保留的最快源数'
        required: false
        default: '20'
      proxy:
        description: '代理地址（如 http://127.0.0.1:10808，可选）'
        required: false
        default: ''
  schedule:
    # 每天凌晨3点自动运行
    - cron: '0 19 * * *'   # UTC时间，北京时间+8小时 = 北京时间3点

jobs:
  update-unicast:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run unicast.py to generate IPTV files
        run: |
          mkdir -p output
          if [ -z "${{ github.event.inputs.top }}" ]; then
            TOP_ARG="--top 20"
          else
            TOP_ARG="--top ${{ github.event.inputs.top }}"
          fi

          if [ -z "${{ github.event.inputs.proxy }}" ]; then
            PROXY_ARG=""
          else
            PROXY_ARG="--proxy ${{ github.event.inputs.proxy }}"
          fi

          python3 mobileunicast/unicast.py $TOP_ARG $PROXY_ARG

      - name: Commit and Push Generated Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新: 重新生成iptv.m3u和iptv.txt"
          branch: ${{ github.ref_name }}
          file_pattern: output/iptv.m3u output/iptv.txt mobileunicast/speed.log mobileunicast/txt.tmp
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Show results
        run: |
          ls -lh output/
