name: 更新IPTV直播源

# 触发条件：每天自动运行 + 手动触发
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点运行（北京时间16点）
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v3
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: 运行直播源处理脚本
        run: |
          python unicast.py --top 20
          
      - name: 检查输出文件
        run: |
          ls -l output/
          
      - name: 提交更新到仓库
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '自动更新IPTV直播源'
          file_pattern: 'output/* speed.log txt.tmp'
          push_options: '--force'
