name: 更新UDPXY服务器源

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      udpxyServer:
        description: 'UDPXY服务器地址 (格式: IP:PORT)'
        required: true
        default: '127.0.0.1:8098'
      testCount:
        description: '每个组播文件测试的地址数量'
        required: false
        default: '20'
      timeout:
        description: '测试超时时间(秒)'
        required: false
        default: '5'
  
  # 自动更新 - 每天凌晨2点运行
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 拉取代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: 运行生成器
      run: |
        # 使用手动输入的服务器地址，如果没有则使用默认值
        UDPSXY_SERVER="${{ github.event.inputs.udpxyServer || '127.0.0.1:8098' }}"
        TEST_COUNT="${{ github.event.inputs.testCount || '20' }}"
        TIMEOUT="${{ github.event.inputs.timeout || '5' }}"
        
        python udpxysourcemake.py $UDPSXY_SERVER --test-count $TEST_COUNT --timeout $TIMEOUT --force-update
        
    - name: 检查输出文件
      run: |
        echo "生成的文件列表："
        ls -l output/
        
    - name: 提交更新
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '自动更新IPTV源'
        file_pattern: 'output/*.m3u output/*.txt'
        commit_user_name: 'GitHub Actions'
        commit_user_email: 'actions@github.com'
